In [ ]:
# 1. Download Automobile dataset from the UCI ML repository

!pip install ucimlrepo

from ucimlrepo import fetch_ucirepo

# fetch dataset
automobile = fetch_ucirepo(id=10)

In [ ]:
# 2. Create pandas dataset with the following columns: X1 (wheel-base), X2 (compression-ratio), X3 (engine-size), X4 (length), X5 (width), Y (city-mpg)
import pandas as pd

df = pd.DataFrame()
df[['X1', 'X2', 'X3', 'X4', 'X5', 'Y']] = automobile.data.features[['wheel-base', 'compression-ratio','engine-size', 'length', 'width', 'city-mpg']]
df.loc[-1] = ['wheel-base', 'compression-ratio','engine-size', 'length', 'width', 'city-mpg']
df.index = df.index + 1
df.sort_index(inplace=True)

In [ ]:
# 3. Designate the first 60% of data as a training set, the next 20% as a validation set, and the last 20% as a test set. You can keep column Y as a part of dataset or separate it into a stand-alone vector.

x_train = df[['X1', 'X2', 'X3', 'X4', 'X5']].iloc[0:int(len(df)*0.6)]
y_train = df['Y'].iloc[0:int(len(df)*0.6)]

x_val = df[['X1', 'X2', 'X3', 'X4', 'X5']].iloc[int(len(df)*0.6):int(len(df)*0.8)]
y_val = df['Y'].iloc[int(len(df)*0.6):int(len(df)*0.8)]

x_test = df[['X1', 'X2', 'X3', 'X4', 'X5']].iloc[int(len(df)*0.8):]
y_test = df['Y'].iloc[int(len(df)*0.8):]


In [ ]:
from sklearn.model_selection import train_test_split

x_train, x_temp, y_train, y_temp = train_test_split(df[['X1', 'X2', 'X3', 'X4', 'X5']][1:], df['Y'][1:], test_size=0.4, random_state=17)

# Split the rest of the 40% in 20% validation and 20% test
x_val, x_test, y_val, y_test = train_test_split(x_temp, y_temp, test_size=0.5, random_state=17)

In [ ]:
# 4. Consider three linear models for the regression problem – linear regression, ridge regression, and LASSO. Fit them with default parameters on the training set and estimate performance
# on both valida3on and test sets. Use MSE, Pearson Correla3on Coefficient (PCC), and Coefficient of determina3on (R2 ) metrics.
from sklearn import linear_model, metrics
from scipy import stats
import numpy as np

In [ ]:
## Linear Regression

from sklearn import linear_model

reg = linear_model.LinearRegression()
reg.fit(x_train[1:], y_train[1:])

y_val_pred = reg.predict(x_val)

mse = metrics.mean_squared_error(y_val, y_val_pred)
pcc = stats.pearsonr(y_val, y_val_pred)[0]
r2 = metrics.r2_score(y_val, y_val_pred)

print("Validation")
print("MSE: " + str(mse) + ", Pearson Correlation Coefficient: " + str(pcc) + ", Coefficient of Determination (R^2) " + str(r2))

y_test_pred = reg.predict(x_test)

mse = metrics.mean_squared_error(y_test, y_test_pred)
pcc = stats.pearsonr(y_test, y_test_pred)[0]
r2 = metrics.r2_score(y_test, y_test_pred)

print("Test")
print("MSE: " + str(mse) + ", Pearson Correlation Coefficient: " + str(pcc) + ", Coefficient of Determination (R^2) " + str(r2))

Validation
MSE: 12.31327336318811, Pearson Correlation Coefficient: 0.8873384039374972, Coefficient of Determination (R^2) 0.7317164490419015
Test
MSE: 6.79947209434839, Pearson Correlation Coefficient: 0.8826049747382002, Coefficient of Determination (R^2) 0.7753378294166278


In [ ]:
## Ridge Regression default lambda

reg_ridge_df = linear_model.Ridge()
reg_ridge_df.fit(x_train[1:], y_train[1:])

y_val_pred = reg_ridge_df.predict(x_val)

mse = metrics.mean_squared_error(y_val, y_val_pred)
pcc = stats.pearsonr(y_val, y_val_pred)[0]
r2 = metrics.r2_score(y_val, y_val_pred)

print("Validation")
print("MSE: " + str(mse) + ", Pearson Correlation Coefficient: " + str(pcc) + ", Coefficient of Determination (R^2) " + str(r2))

y_test_pred = reg_ridge_df.predict(x_test)

mse = metrics.mean_squared_error(y_test, y_test_pred)
pcc = stats.pearsonr(y_test, y_test_pred)[0]
r2 = metrics.r2_score(y_test, y_test_pred)

print("Test")
print("MSE: " + str(mse) + ", Pearson Correlation Coefficient: " + str(pcc) + ", Coefficient of Determination (R^2) " + str(r2))

Validation
MSE: 12.316444787627088, Pearson Correlation Coefficient: 0.8873279385093951, Coefficient of Determination (R^2) 0.731647349543743
Test
MSE: 6.801673505684433, Pearson Correlation Coefficient: 0.8825699516116872, Coefficient of Determination (R^2) 0.7752650923214182


In [ ]:
## LASSO Regression default lambda

reg_lasso_df = linear_model.Lasso()
reg_lasso_df.fit(x_train[1:], y_train[1:])

y_val_pred = reg_lasso_df.predict(x_val)
mse = metrics.mean_squared_error(y_val, y_val_pred)
pcc = stats.pearsonr(y_val, y_val_pred)[0]
r2 = metrics.r2_score(y_val, y_val_pred)

print("Validation")
print("MSE: " + str(mse) + ", Pearson Correlation Coefficient: " + str(pcc) + ", Coefficient of Determination (R^2) " + str(r2))

y_test_pred = reg_lasso_df.predict(x_test)

mse = metrics.mean_squared_error(y_test, y_test_pred)
pcc = stats.pearsonr(y_test, y_test_pred)[0]
r2 = metrics.r2_score(y_test, y_test_pred)

print("Test")
print("MSE: " + str(mse) + ", Pearson Correlation Coefficient: " + str(pcc) + ", Coefficient of Determination (R^2) " + str(r2))

Validation
MSE: 13.244168626946609, Pearson Correlation Coefficient: 0.8768569340474097, Coefficient of Determination (R^2) 0.7114339555436379
Test
MSE: 8.108793011387235, Pearson Correlation Coefficient: 0.86037642314003, Coefficient of Determination (R^2) 0.7320764004217718


In [ ]:
# 5. For ridge regression and LASSO inves3gate the following values of parameter alpha (mul3plica3on coefficient for regulariza3on) on the valida3on set and its effect on model performance: [0., 0.25, 0.5, 1., 1000.].
# Which value gives the best performance on the valida3on set? Retrain the model with this value and calculate the same metrics on the test set

alpha = [0, 0.25, 0.5, 1, 1000]

# Ridge Regression
print("Ridge Regression")

ridge_coefs = []
lasso_coefs = []

for l in alpha:

  print("For lambda = " + str(l))

  reg_ridge = linear_model.Ridge(alpha=l)
  reg_ridge.fit(x_train[1:], y_train[1:])
  ridge_coefs.append(reg_ridge.coef_)


  y_val_pred = reg_ridge.predict(x_val)

  mse = metrics.mean_squared_error(y_val, y_val_pred)
  pcc = stats.pearsonr(y_val, y_val_pred)[0]
  r2 = metrics.r2_score(y_val, y_val_pred)

  print("MSE: " + str(mse) + ", Pearson Correlation Coefficient: " + str(pcc) + ", Coefficient of Determination (R^2) " + str(r2))


print("Best performance for lambda = 1")

reg_ridge = linear_model.Ridge(alpha=1000)
reg_ridge.fit(x_train[1:], y_train[1:])

y_test_pred = reg_ridge.predict(x_test)

mse = metrics.mean_squared_error(y_test, y_test_pred)
pcc = stats.pearsonr(y_test, y_test_pred)[0]
r2 = metrics.r2_score(y_test, y_test_pred)

print("Test")
print("MSE: " + str(mse) + ", Pearson Correlation Coefficient: " + str(pcc) + ", Coefficient of Determination (R^2) " + str(r2))

# LASSO Regression

print("-----------------------------------------------")
print("LASSO Regression")


for l in alpha:

  print("For lambda = " + str(l))

  reg_lasso = linear_model.Lasso(alpha=l)
  reg_lasso.fit(x_train[1:], y_train[1:])
  lasso_coefs.append(reg_lasso.coef_)

  y_val_pred = reg_lasso.predict(x_val)

  mse = metrics.mean_squared_error(y_val, y_val_pred)
  pcc = stats.pearsonr(y_val, y_val_pred)[0]
  r2 = metrics.r2_score(y_val, y_val_pred)

  print("MSE: " + str(mse) + ", Pearson Correlation Coefficient: " + str(pcc) + ", Coefficient of Determination (R^2) " + str(r2))

print("Best performance for lambda = 0.25")

reg_lasso = linear_model.Lasso(alpha=0.25)
reg_lasso.fit(x_train[1:], y_train[1:])

y_test_pred = reg_lasso.predict(x_test)

mse = metrics.mean_squared_error(y_test, y_test_pred)
pcc = stats.pearsonr(y_test, y_test_pred)[0]
r2 = metrics.r2_score(y_test, y_test_pred)

print("Test")
print("MSE: " + str(mse) + ", Pearson Correlation Coefficient: " + str(pcc) + ", Coefficient of Determination (R^2) " + str(r2))

print("-----------------------------------------------")
print("Coefficients for Ridge Regression")
print(np.array(ridge_coefs))
print("Coefficients for Lasso Regression")
print(np.array(lasso_coefs))


Ridge Regression
For lambda = 0
MSE: 12.313273363188094, Pearson Correlation Coefficient: 0.8873384039374971, Coefficient of Determination (R^2) 0.7317164490419019
For lambda = 0.25
MSE: 12.314066475777276, Pearson Correlation Coefficient: 0.8873358184634501, Coefficient of Determination (R^2) 0.7316991685791476
For lambda = 0.5
MSE: 12.31485942237031, Pearson Correlation Coefficient: 0.8873332122419703, Coefficient of Determination (R^2) 0.7316818917331438
For lambda = 1
MSE: 12.316444787627088, Pearson Correlation Coefficient: 0.8873279385093951, Coefficient of Determination (R^2) 0.731647349543743
For lambda = 1000
MSE: 13.973383280274506, Pearson Correlation Coefficient: 0.8750435098866928, Coefficient of Determination (R^2) 0.6955457111398091
Best performance for lambda = 1
Test
MSE: 8.20376686874833, Pearson Correlation Coefficient: 0.8558555377133944, Coefficient of Determination (R^2) 0.7289383578432671
-----------------------------------------------
LASSO Regression
For lambda

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:1152: UserWarning: With alpha=0, this algorithm does not converge well. You are advised to use the LinearRegression estimator
  return fit_method(estimator, *args, **kwargs)
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:628: UserWarning: Coordinate descent with no regularization may lead to unexpected results and is discouraged.
  model = cd_fast.enet_coordinate_descent(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.260e+02, tolerance: 5.499e-01 Linear regression models with null weight for the l1 regularization term are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.
  model = cd_fast.enet_coordinate_descent

In [ ]:
#6. Apply Scikit-Learn function PolynomialFeatures to the feature part of the dataset (columns X 1 - X 5 ), use the degree 5. Column Y should not be transformed!

from sklearn.preprocessing import PolynomialFeatures

poly = PolynomialFeatures(5)
x_train_tf = poly.fit_transform(x_train[1:])
x_val_tf = poly.transform(x_val)
x_test_tf = poly.transform(x_test)

In [ ]:
alpha = [0, 0.25, 0.5, 1, 1000]

ridge_coefs_poly = []
lasso_coefs_poly = []

# Ridge Regression
print("Ridge Regression")

for l in alpha:

  print("For lambda = " + str(l))

  reg_ridge_poly = linear_model.Ridge(alpha=l)
  reg_ridge_poly.fit(x_train_tf, y_train[1:])
  ridge_coefs_poly.append(reg_ridge_poly.coef_)


  y_val_pred = reg_ridge_poly.predict(x_val_tf)

  mse = metrics.mean_squared_error(y_val, y_val_pred)
  pcc = stats.pearsonr(y_val, y_val_pred)[0]
  r2 = metrics.r2_score(y_val, y_val_pred)

  print("MSE: " + str(mse) + ", Pearson Correlation Coefficient: " + str(pcc) + ", Coefficient of Determination (R^2) " + str(r2))


print("Same performance for all lambda values")
reg_ridge_poly = linear_model.Ridge(alpha=1)
reg_ridge_poly.fit(x_train_tf, y_train[1:])

y_test_pred = reg_ridge_poly.predict(x_test_tf)

mse = metrics.mean_squared_error(y_test, y_test_pred)
pcc = stats.pearsonr(y_test, y_test_pred)[0]
r2 = metrics.r2_score(y_test, y_test_pred)

print("Test")
print("MSE: " + str(mse) + ", Pearson Correlation Coefficient: " + str(pcc) + ", Coefficient of Determination (R^2) " + str(r2))

# LASSO Regression

print("-----------------------------------------------")
print("LASSO Regression")

for l in alpha:

  print("For lambda = " + str(l))

  reg_lasso_poly = linear_model.Lasso(alpha=l)
  reg_lasso_poly.fit(x_train_tf, y_train[1:])
  lasso_coefs_poly.append(reg_lasso_poly.coef_)

  y_val_pred = reg_lasso_poly.predict(x_val_tf)

  mse = metrics.mean_squared_error(y_val, y_val_pred)
  pcc = stats.pearsonr(y_val, y_val_pred)[0]
  r2 = metrics.r2_score(y_val, y_val_pred)

  print("MSE: " + str(mse) + ", Pearson Correlation Coefficient: " + str(pcc) + ", Coefficient of Determination (R^2) " + str(r2))


print("Best performance for lambda = 1")

reg_lasso_poly = linear_model.Lasso(alpha=1)
reg_lasso_poly.fit(x_train_tf, y_train[1:])

y_test_pred = reg_lasso_poly.predict(x_test_tf)

mse = metrics.mean_squared_error(y_test, y_test_pred)
pcc = stats.pearsonr(y_test, y_test_pred)[0]
r2 = metrics.r2_score(y_test, y_test_pred)

print("Test")
print("MSE: " + str(mse) + ", Pearson Correlation Coefficient: " + str(pcc) + ", Coefficient of Determination (R^2) " + str(r2))


print("-----------------------------------------------")
print("Coefficients for Ridge Regression")
print(np.array(ridge_coefs_poly))
print("Coefficients for Lasso Regression")
print(np.array(lasso_coefs_poly))

Ridge Regression
For lambda = 0
MSE: 545.5884544703384, Pearson Correlation Coefficient: -0.15459017836103425, Coefficient of Determination (R^2) -10.887367689296958
For lambda = 0.25
MSE: 545.5884544703384, Pearson Correlation Coefficient: -0.15459017836103425, Coefficient of Determination (R^2) -10.887367689296958
For lambda = 0.5
MSE: 545.5884544703384, Pearson Correlation Coefficient: -0.15459017836103425, Coefficient of Determination (R^2) -10.887367689296958
For lambda = 1


/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_ridge.py:239: UserWarning: Singular matrix in solving dual problem. Using least-squares solution instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_ridge.py:239: UserWarning: Singular matrix in solving dual problem. Using least-squares solution instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_ridge.py:239: UserWarning: Singular matrix in solving dual problem. Using least-squares solution instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_ridge.py:239: UserWarning: Singular matrix in solving dual problem. Using least-squares solution instead.
  warnings.warn(


MSE: 545.5884544703384, Pearson Correlation Coefficient: -0.15459017836103425, Coefficient of Determination (R^2) -10.887367689296958
For lambda = 1000
MSE: 545.5884544703384, Pearson Correlation Coefficient: -0.15459017836103425, Coefficient of Determination (R^2) -10.887367689296958
Same performance for all lambda values
Test
MSE: 42596.295142784285, Pearson Correlation Coefficient: -0.2597905994157211, Coefficient of Determination (R^2) -1406.4292816852815
-----------------------------------------------
LASSO Regression
For lambda = 0
MSE: 10.478610912212096, Pearson Correlation Coefficient: 0.9028489978814667, Coefficient of Determination (R^2) 0.7716903652085684
For lambda = 0.25
MSE: 10.340121245564887, Pearson Correlation Coefficient: 0.9039302217571987, Coefficient of Determination (R^2) 0.7747078000078471
For lambda = 0.5


/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_ridge.py:239: UserWarning: Singular matrix in solving dual problem. Using least-squares solution instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_ridge.py:239: UserWarning: Singular matrix in solving dual problem. Using least-squares solution instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/base.py:1152: UserWarning: With alpha=0, this algorithm does not converge well. You are advised to use the LinearRegression estimator
  return fit_method(estimator, *args, **kwargs)
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:628: UserWarning: Coordinate descent with no regularization may lead to unexpected results and is discouraged.
  model = cd_fast.enet_coordinate_descent(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increas

MSE: 10.382919144841528, Pearson Correlation Coefficient: 0.9036245120031621, Coefficient of Determination (R^2) 0.7737753125974879
For lambda = 1
MSE: 10.34893501478794, Pearson Correlation Coefficient: 0.9039413360681199, Coefficient of Determination (R^2) 0.7745157642075574
For lambda = 1000
MSE: 10.617358764453224, Pearson Correlation Coefficient: 0.9037905470543113, Coefficient of Determination (R^2) 0.7686673050206622
Best performance for lambda = 1
Test
MSE: 5.605078045296888, Pearson Correlation Coefficient: 0.9132805815298018, Coefficient of Determination (R^2) 0.8148019460227992
-----------------------------------------------
Coefficients for Ridge Regression
[[ 0.00000000e+00  3.03549067e-12  5.00292683e-13 ... -2.20449350e-05
  -1.41629031e-05  2.05204468e-05]
 [ 0.00000000e+00  3.03549067e-12  5.00292683e-13 ... -2.20449350e-05
  -1.41629031e-05  2.05204468e-05]
 [ 0.00000000e+00  3.03549067e-12  5.00292683e-13 ... -2.20449350e-05
  -1.41629031e-05  2.05204468e-05]
 [ 0.00

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.869e+02, tolerance: 5.499e-01
  model = cd_fast.enet_coordinate_descent(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.943e+02, tolerance: 5.499e-01
  model = cd_fast.enet_coordinate_descent(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.421e+02, tolerance: 5.499e

In [ ]:
# 8. Analyze coefficients of Ridge regression and LASSO models. What is the most important feature (a feature having the largest weight)? Which features have weights close to zero?

print(np.array(ridge_coefs))

print(np.array(lasso_coefs))

print("The most important feature is X2: compression ratio, while the closest to 0 is X3: engine size")<

[[ 0.33921115  0.65799479 -0.02052991 -0.36465456 -0.81017737]
 [ 0.33898983  0.65790891 -0.0205569  -0.36468208 -0.8088911 ]
 [ 0.338769    0.65782307 -0.02058382 -0.36470939 -0.80760891]
 [ 0.33832885  0.65765153 -0.02063741 -0.36476337 -0.80505668]
 [ 0.11284946  0.43600473 -0.04177591 -0.30002006 -0.1157424 ]]
[[ 0.33921115  0.65799479 -0.02052991 -0.36465456 -0.81017737]
 [ 0.28050967  0.64644997 -0.02488934 -0.35751498 -0.61519372]
 [ 0.22188604  0.63489445 -0.0292469  -0.35042059 -0.42017534]
 [ 0.10471133  0.61177308 -0.03796054 -0.33627514 -0.03009657]
 [-0.          0.         -0.         -0.         -0.        ]]
The most important feature is X2: compression ratio, while the closest to 0 is X3: engine size
